
package com.indus.training.service;

import javax.jws.WebService;
import javax.xml.ws.BindingType;
import com.indus.training.domain.inout.CalIn;
import com.indus.training.domain.inout.CalOut;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.2.11-b150616.1732
 * Generated source version: 2.2
 * 
 */
@WebService(portName = "CalciServicePort", serviceName = "CalciService", targetNamespace = "http://service.training.indus.com/", wsdlLocation = "/wsdls/CalcWSDL.wsdl", endpointInterface = "com.indus.training.service.ICalci")
@BindingType("http://schemas.xmlsoap.org/wsdl/soap/http")
public class CalciService_CalciServicePortImpl implements ICalci {

	private Calci calobj;
	
	public CalciService_CalciServicePortImpl() {
	}

	/**
	 * 
	 * @param calInObj
	 * @return returns com.indus.training.domain.inout.CalOut
	 */
	public CalOut addition(CalIn calInObj) {
		CalOut resultObj = null;
		
		calobj = new Calci();
		
		resultObj = new CalOut();
		
		resultObj.setResult(calobj.addition(calInObj.getParam1(), calInObj.getParam2()));
		
		resultObj.setParam1(calInObj.getParam1());
		resultObj.setParam2(calInObj.getParam2());
		
		return resultObj;
	}

}
