//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 06:11:56 PM EDT 
//


package com.indus.training.persons;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.indus.training.xsd.persons package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Persons_QNAME = new QName("http://persons.xsd.training.indus.com/", "persons");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.indus.training.xsd.persons
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Persons }
     * 
     */
    public Persons createPersons() {
        return new Persons();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Persons }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://persons.xsd.training.indus.com/", name = "persons")
    public JAXBElement<Persons> createPersons(Persons value) {
        return new JAXBElement<Persons>(_Persons_QNAME, Persons.class, null, value);
    }

}
