<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:CalWsdl="http://service.training.indus.com/"
 xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" 
 xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns:CalSchema="http://inout.domain.training.indus.com/" 
   name="CalcWSDL" targetNamespace="http://service.training.indus.com/">
 
 
  <wsdl:types>
   <xsd:schema>
   <xsd:import namespace="http://inout.domain.training.indus.com/" schemaLocation="../xsd/CalcInOut.xsd" />
   
   </xsd:schema>
  </wsdl:types>
 
 
  <wsdl:message name="calciRequestMsg">
    <wsdl:part element="CalSchema:CalInEl" name="calInObj"/>
  </wsdl:message>
 
 
  <wsdl:message name="calciResponseMsg">
    <wsdl:part element="CalSchema:CalOutEl" name="resultObj"/>
  </wsdl:message>
 
 
  <wsdl:portType name="ICalci">
    <wsdl:operation name="Addition">
      <wsdl:input message="CalWsdl:calciRequestMsg"/>
      <wsdl:output message="CalWsdl:calciResponseMsg"/>
    </wsdl:operation>
  </wsdl:portType>
 
 
  <wsdl:binding name="CalcWSDLSOAP" type="CalWsdl:ICalci">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="Addition">
      <soap:operation soapAction="http://service.training.indus.com/Addition"/>
      <wsdl:input>
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output>
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  
  
  <wsdl:service name="CalciService">
    <wsdl:port binding="CalWsdl:CalcWSDLSOAP" name="CalciServicePort">
      <soap:address location="http://localhost:9010/IndusTrainingWebService5/CalciService"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
