//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.03.20 at 06:11:56 PM EDT 
//


package com.indus.training.xsd.persons;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import com.indus.training.xsd.person.Person;


/**
 * <p>Java class for Persons complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Persons">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="oneperson" type="{http://person.xsd.training.indus.com/}Person"/>
 *         &lt;element name="twoperson" type="{http://person.xsd.training.indus.com/}Person"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Persons", propOrder = {
    "oneperson",
    "twoperson"
})
public class Persons {

    @XmlElement(required = true)
    protected Person oneperson;
    @XmlElement(required = true)
    protected Person twoperson;

    /**
     * Gets the value of the oneperson property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getOneperson() {
        return oneperson;
    }

    /**
     * Sets the value of the oneperson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setOneperson(Person value) {
        this.oneperson = value;
    }

    /**
     * Gets the value of the twoperson property.
     * 
     * @return
     *     possible object is
     *     {@link Person }
     *     
     */
    public Person getTwoperson() {
        return twoperson;
    }

    /**
     * Sets the value of the twoperson property.
     * 
     * @param value
     *     allowed object is
     *     {@link Person }
     *     
     */
    public void setTwoperson(Person value) {
        this.twoperson = value;
    }

}
